### ISSUE TITLE
7-3 启用节点绕过 遇到的现象 

### ISSUE THREAD

**Issue by lambdaplus** [juewuy/ShellClash#348]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

##### 1、开启`7-3`之前的配置文件 `rule` 部分如下：

```yaml
rules:
 - RULE-SET,applications,DIRECT
 - DOMAIN-SUFFIX,sslip.io,DIRECT
 - DOMAIN,yacd.haishan.me,DIRECT
 - DOMAIN,clash.razord.top,DIRECT
 - DOMAIN-SUFFIX,twimg.com,Streaming
 - DOMAIN-SUFFIX,openai.com,OpenAI
 - DOMAIN,ai.com,OpenAI
 - DOMAIN-SUFFIX,services.googleapis.cn,Streaming
 - RULE-SET,private,DIRECT
 - RULE-SET,reject,REJECT
 - RULE-SET,Biliintl,StreamingSE
 - RULE-SET,StreamingSE,StreamingSE
 - RULE-SET,Streaming,Streaming
 - RULE-SET,icloud,DIRECT
 - RULE-SET,apple,DIRECT
 - RULE-SET,google,Streaming
 - RULE-SET,proxy,PROXY
 - RULE-SET,direct,DIRECT
 - RULE-SET,lancidr,DIRECT
 - RULE-SET,cncidr,DIRECT
 - RULE-SET,telegramcidr,Streaming
 - GEOIP,LAN,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,PROXY
```
这些规则我配置文件中的正常内容。

##### 2、开启`7-3`之后，`rule` 部分被修饰成如下：

```yaml
rules:
 - DOMAIN,huawei.kqskunlun.xyz,DIRECT #节点绕过
 - DOMAIN,www.gstatic.com,DIRECT #节点绕过
 - DOMAIN,sub.xflash.cc,DIRECT #节点绕过
 - DOMAIN,XFLASH.yaml,DIRECT #节点绕过
 - DOMAIN,mf.rsssub.top,DIRECT #节点绕过
 - DOMAIN,MoFast.yaml,DIRECT #节点绕过
 - DOMAIN,cdn.jsdelivr.net,DIRECT #节点绕过
 - DOMAIN,reject.txt,DIRECT #节点绕过
 - DOMAIN,reject.yaml,DIRECT #节点绕过
 - DOMAIN,icloud.txt,DIRECT #节点绕过
 - DOMAIN,icloud.yaml,DIRECT #节点绕过
 - DOMAIN,apple.txt,DIRECT #节点绕过
 - DOMAIN,apple.yaml,DIRECT #节点绕过
 - DOMAIN,google.txt,DIRECT #节点绕过
 - DOMAIN,google.yaml,DIRECT #节点绕过
 - DOMAIN,proxy.txt,DIRECT #节点绕过
 - DOMAIN,proxy.yaml,DIRECT #节点绕过
 - DOMAIN,direct.txt,DIRECT #节点绕过
 - DOMAIN,direct.yaml,DIRECT #节点绕过
 - DOMAIN,private.txt,DIRECT #节点绕过
 - DOMAIN,private.yaml,DIRECT #节点绕过
 - DOMAIN,gfw.txt,DIRECT #节点绕过
 - DOMAIN,gfw.yaml,DIRECT #节点绕过
 - DOMAIN,telegramcidr.txt,DIRECT #节点绕过
 - DOMAIN,telegramcidr.yaml,DIRECT #节点绕过
 - DOMAIN,cncidr.txt,DIRECT #节点绕过
 - DOMAIN,cncidr.yaml,DIRECT #节点绕过
 - DOMAIN,lancidr.txt,DIRECT #节点绕过
 - DOMAIN,lancidr.yaml,DIRECT #节点绕过
 - DOMAIN,applications.txt,DIRECT #节点绕过
 - DOMAIN,applications.yaml,DIRECT #节点绕过
 - DOMAIN,StreamingSE.yaml,DIRECT #节点绕过
 - DOMAIN,github.com,DIRECT #节点绕过
 - DOMAIN,Streaming.yaml,DIRECT #节点绕过
 - DOMAIN,Biliintl.yaml,DIRECT #节点绕过
 - DOMAIN,BiliBiliIntl.yaml,DIRECT #节点绕过
 - RULE-SET,applications,DIRECT
 - DOMAIN-SUFFIX,sslip.io,DIRECT
 - DOMAIN,yacd.haishan.me,DIRECT
 - DOMAIN,clash.razord.top,DIRECT
 - DOMAIN-SUFFIX,twimg.com,Streaming
 - DOMAIN-SUFFIX,openai.com,OpenAI
 - DOMAIN,ai.com,OpenAI
 - DOMAIN-SUFFIX,services.googleapis.cn,Streaming
 - RULE-SET,private,DIRECT
 - RULE-SET,reject,REJECT
 - RULE-SET,Biliintl,StreamingSE
 - RULE-SET,StreamingSE,StreamingSE
 - RULE-SET,Streaming,Streaming
 - RULE-SET,icloud,DIRECT
 - RULE-SET,apple,DIRECT
 - RULE-SET,google,Streaming
 - RULE-SET,proxy,PROXY
 - RULE-SET,direct,DIRECT
 - RULE-SET,lancidr,DIRECT
 - RULE-SET,cncidr,DIRECT
 - RULE-SET,telegramcidr,Streaming
 - GEOIP,LAN,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,PROXY
```
也就是把`config.yaml`里 `proxy-providers`、`proxy-groups`、`rule-providers`这三个配置中`.` 前后的内容当成`DOMAIN`规则添加进了 `rule`，甚至在
```yaml  
Streaming:
    type: http
    behavior: classical
    path: ./ruleset/Streaming.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
# https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
  Biliintl:
    type: http
    behavior: classical
    path: ./ruleset/Biliintl.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBiliIntl/BiliBiliIntl.yaml"
    interval: 86400
```
注释中的链接`# https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml`中的`github.com`都`#节点绕过`了。导致浏览器上GitHub出现问题，昨天排查了好长时间都没解决，今天突然想到`#节点绕过`才解决。

##### 3、告知大家一下，占用版面，打扰作者了，还请见谅。
