### ISSUE TITLE
[Bug]  Overly strict config validation

### ISSUE THREAD

**Issue by LaplaceTor** [juewuy/ShellClash#365]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description
My config looks like 

```
proxies:
    name: HKT
    server: hk
    port: 15
    type: vmess
    uuid: 31
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true

```
Then it told me that alterId missing, fixed with rewrite `uuid: 31` to `uuid: '31'`

Each extra line for reading would get a reply that it ask for an expect word `,` or `}`

Shellclash Version 1.7.4d
