### ISSUE TITLE
[Bug] 一个小的预处理后的配置文件格式问题

### ISSUE THREAD

**Issue by zhihans** [juewuy/ShellClash#389]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

配置文件中`sub-rules`位置在`rules`前面时，启动会报错。
```
error msg="yaml: line 123: did not find expected key"
```

然后我查看了`config.yaml`,发现处理后的配置文件中sub-rules部分少了一个空格。
```yaml
sub-rules:
  fcm:
 - DST-PORT,5228/5229/5230,📢 谷歌FCM
  speedtest:
 - NOT,((DOMAIN-SUFFIX,cn)),☑️ 节点选择
  quic:
 - AND,((NOT,((GEOSITE,CN))),(NOT,((GEOIP,CN))),(DST-PORT,443)),REJECT
```
当我把sub-rules在rules前面时就正常
```yaml
sub-rules:
  fcm:
    - DST-PORT,5228/5229/5230,📢 谷歌FCM
  speedtest:
    - NOT,((DOMAIN-SUFFIX,cn)),☑️ 节点选择
  quic:
    - AND,((NOT,((GEOSITE,CN))),(NOT,((GEOIP,CN))),(DST-PORT,443)),REJECT
```
