### ISSUE TITLE
自定义设定配置文件user.yaml和菜单7-6内置的DNS服务优先级的疑问

### ISSUE THREAD

**Issue by Jefffish09** [juewuy/ShellClash#430]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash版本：1.7.9f测试版

有个疑问，假如我在菜单7-6-1修改为dns 1，7-6-2修改为dns 2

然后又修改了user.yaml，在里面修改为
```
...
nameserver:
    - dns 3
fallback: 
    - dns 4
fallback-filter:
    geoip: true
    geoip-code: CN
...
```
那么最终clash的dns究竟会怎样分流？优先用user.yaml里面的配置，还是菜单7-6里面？
