### ISSUE TITLE
[Bug] Ubuntu 22.04.2 LTS 版本：1.7.10e tun模式无效。

### ISSUE THREAD

**Issue by WilsonVincent** [juewuy/ShellClash#460]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

欢迎使用ShellClash！            版本：1.7.10e
Clash服务正在运行（纯净模式），已设置开机启动！
当前内存占用：33232 kB，已运行：00小时01分08秒

问题：使用纯净模式下，在面板中开启tun转发无法保存。重启后又需要手动二次开启。
问题：如果使用tun模式，在Ubuntu中无效，完全不起作用。直接纯净模式+面板开启tun转发有效，但是无法保存。
问题：面板上其他配置我尝试修改后保存，均重启后还原，并且端口修改无效。

@juewuy

**Comment by juewuy** [comment]
@WilsonVincent 面板只支持保存节点选择，其他模式都会绕过本机，本机代理必须单独开启

**Comment by WilsonVincent** [comment]
> @WilsonVincent 面板只支持保存节点选择，其他模式都会绕过本机，本机代理必须单独开启
@juewuy 
没有啊。面板可以开启tun转发。但是重启就无法自动开启必须手动开启。
我需要开机后直接启动tun。有什么办法吗？

**Comment by juewuy** [comment]
@WilsonVincent 脚本有内置的tun模式

**Comment by WilsonVincent** [comment]
> @WilsonVincent 脚本有内置的tun模式

@juewuy 

内置的tun我启动后无法使用。我回退f版有用。。刚刚我试了一下。

**Comment by juewuy** [comment]
可以使用6-6添加自定义配置

**Comment by WilsonVincent** [comment]
@juewuy 
 ```
 1 自定义端口及秘钥
 2 管理自定义规则
 3 管理自定义节点
 4 管理自定义策略组
 5 自定义高级功能
 9 禁用配置文件覆写
 ```
 请问一下是具体是6-6的哪一个里面进行配置？tun模式需要如何配置？是否有参考的配置样例？

**Comment by juewuy** [comment]
@WilsonVincent 5

**Comment by WilsonVincent** [comment]
> @WilsonVincent 5

@juewuy 辛苦能否提供一点参考性的配置示范？

**Comment by juewuy** [comment]
@WilsonVincent 脚本有提示官方wiki链接

**Comment by WilsonVincent** [comment]
```
tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

```

是这一份吗？

**Comment by WilsonVincent** [comment]
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 223.5.5.5
    - 114.114.114.114
  fallback:
    - 8.8.4.4
    - 223.6.6.6
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

@juewuy 
我把电脑上的这一份配置粘贴进去是否可以生效？
