### ISSUE TITLE
内网 DNS 无法解析问题

### ISSUE THREAD

**Issue by lvii** [juewuy/ShellClash#79]
Hi

在 openwrt 上安装好 shellclash 后，公网域名解析没有问题，但是 **内网** 域名无法解析：

``` yaml
dns:
  enable: true
  listen: ':1053'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  nameserver:
    - 172.24.100.2                <-- 内网 DNS 路由器 DHCP 的 /etc/resolv.conf
    - 127.0.0.1:53                <-- DNSmasq
    - tls://dns.rubyfish.cn:853
    - https://dns.alidns.com/dns-query

  nameserver-policy:
    '+.example-inc.com': '172.24.100.2'

  # # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  # fake-ip-filter:
  #   - '*.lan'
  # fallback:
  #   - tcp://1.1.1.1
  #   - tls://dns.google:853
```

`nameserver-policy` 没有生效

也在 `rules:` 规则部分增加 **内网** 域名的 **跳过** 规则：

``` yaml
rules:
- SRC-IP-CIDR,172.24.0.0/16,DIRECT
- DOMAIN-SUFFIX,example-inc.com,DIRECT
```

在 openwrt 上使用 clash 的 DNS 端口无法解析 **内网** `example-inc.com` 域名：

    # dig +short oa.intra.example-inc.com @172.24.100.2
    10.8.12.5

    # dig +short oa.intra.example-inc.com @127.0.0.1 -p 53
    10.8.12.5

    # dig +short oa.intra.example-inc.com @127.0.0.1 -p 1053

﻿
