### ISSUE TITLE
怎么配置实现外网回家？

### ISSUE THREAD

**Issue by zhen-ke** [juewuy/ShellClash#968]
我在老家的路由器上搭的 Shadowsocks 服务器，来访问老家另一个局域网里的设备（比如IP是 192.168.10.1 的设备）。Shadowsocks 节点确认可用，但访问远程内网IP(192.168.10.1)失败。

这我的 ShellCrash 里的 Clash 配置 (部分内容)：
```YAML
proxies:
  - name: 🇨🇳 CN-Home # 我的家庭SS节点的名字
    server: home.abc.xyz # 我的DDNS域名
    port: 7878 
    type: ss          
    cipher: aes-256-gcm 
    password: x123

proxy-groups:
  - name: 🏡 访问家庭网络 # 策略组名字
    type: select
    proxies:
      - 🇨🇳 CN-Home

rules:
  # 访问家庭内网的规则
  - IP-CIDR,192.168.10.0/24,🏡 访问家庭网络,no-resolve
```
这样配置后，始终无法通过🇨🇳 CN-Home 访问家里的 192.168.10.1 ，但 Quantumult X 通过类似这样配置下就能访问家里的服务
